
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "python -m backend.shared.infrastructure.persistence.wait_for_db && 
               uvicorn backend.shared.infrastructure.api.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backenddb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
